apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: shopnow
  labels:
    app: keycloak
    part-of: shopnow
    version: "1.0"
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin-dev-password
