apiVersion: v1
kind: Secret
metadata:
  name: shopnow-oauth2-client-secrets
  namespace: shopnow
  labels:
    app: keycloak
    part-of: shopnow
    version: "1.0"
type: Opaque
stringData:
  API_GATEWAY_CLIENT_SECRET: api-gateway-dev-secret
  ORDER_SERVICE_CLIENT_SECRET: order-service-dev-secret
  PRODUCT_SERVICE_CLIENT_SECRET: product-service-dev-secret
  INVENTORY_SERVICE_CLIENT_SECRET: inventory-service-dev-secret
  USER_SERVICE_CLIENT_SECRET: user-service-dev-secret
  CART_SERVICE_CLIENT_SECRET: cart-service-dev-secret
  NOTIFICATION_SERVICE_CLIENT_SECRET: notification-service-dev-secret
