apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: shopnow
  labels:
    app: keycloak
    part-of: shopnow
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        part-of: shopnow
        version: "1.0"
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.7.0
          imagePullPolicy: IfNotPresent
          args:
            - start-dev
            - --import-realm
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000
          envFrom:
            - secretRef:
                name: keycloak-admin
          env:
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import
              readOnly: true
          startupProbe:
            httpGet:
              path: /health/started
              port: management
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: management
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: management
            periodSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "750m"
      volumes:
        - name: realm-import
          secret:
            secretName: keycloak-shopnow-realm
