apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: shopnow
  labels:
    app: keycloak
    part-of: shopnow
    version: "1.0"
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8181
      targetPort: http
    - name: management
      port: 9000
      targetPort: management
