apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: shopnow
  labels:
    app: notification-service
    part-of: shopnow
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        part-of: shopnow
        version: "1.0"
    spec:
      containers:
        - name: notification-service
          image: shopnow/notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
