apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shopnow
  labels:
    app: notification-service
    part-of: shopnow
    version: "1.0"
spec:
  selector:
    app: notification-service
  ports:
    - port: 8086
      targetPort: 8086
