apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shopnow
  labels:
    app: frontend
    part-of: shopnow
    version: "1.0"
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
