apiVersion: v1
kind: ResourceQuota
metadata:
  name: shopnow-quota
  namespace: shopnow
spec:
  hard:
    requests.cpu: "16"
    requests.memory: "10Gi"
    limits.cpu: "10"
    limits.memory: "16Gi"
    pods: "40"