apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: shopnow
  labels:
    app: cart-service
    part-of: shopnow
    version: "1.0"
spec:
  selector:
    app: cart-service
  ports:
    - port: 8085
      targetPort: 8085
