apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: shopnow
  labels:
    app: kafka
    part-of: shopnow
    version: "1.0"
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        part-of: shopnow
        version: "1.0"
    spec:
      containers:
        - name: kafka
          image: bitnamilegacy/kafka:3.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: broker
              containerPort: 9092
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "no"
            - name: KAFKA_CFG_BROKER_ID
              value: "0"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zookeeper.shopnow.svc.cluster.local:2181"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-0.kafka.shopnow.svc.cluster.local:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
        labels:
          app: kafka
          part-of: shopnow
          version: "1.0"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
