apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: shopnow
  labels:
    app: kafka
    part-of: shopnow
    version: "1.0"
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
