apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shopnow
  labels:
    app: redis
    part-of: shopnow
    version: "1.0"
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
