apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: shopnow
  labels:
    app: zipkin
    part-of: shopnow
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
        part-of: shopnow
        version: "1.0"
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
          env:
            - name: STORAGE_TYPE
              value: mem
          startupProbe:
            httpGet:
              path: /health
              port: 9411
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
