apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: shopnow
  labels:
    app: zipkin
    part-of: shopnow
    version: "1.0"
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
