apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: shopnow
  labels:
    app: zookeeper
    part-of: shopnow
    version: "1.0"
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
