spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://config-server:8888"
  kafka:
    bootstrap-servers: kafka-0.kafka.shopnow.svc.cluster.local:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.chol.shopnow.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: dev.chol.shopnow.notification_service.event.OrderPlacedEvent

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
