apiVersion: v1
kind: Service
metadata:
  name: product-service-green-test
  namespace: shopnow
  labels:
    app: product-service
    part-of: shopnow
    version: "1.0"
    slot: green
spec:
  selector:
    app: product-service
    slot: green
  ports:
    - port: 8081
      targetPort: 8081
